name: Submodules Update for Customer Configuration Repositories

on:
  workflow_call:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Submodules Update
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        id: status
        run: |
          git submodule update --remote
          git status -s
          [[ "$(git status -s)" != "" ]] && echo "status=1" >> "$GITHUB_OUTPUT"
      - name: Commit change
        if: ${{ steps.status.outputs.status == 1 }}
        run: |
          git config --global user.name "config-test-updater"
          git config --global user.email "config-test-updater@users.noreply.github.com"
          git add -A
          git commit -m "Automatic submodules update"
          git push origin main
