name: Submodules Update for Customer Configuration Repositories

on:
  workflow_call:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        id: status
        run: |
          git submodule update --remote
          git status -s
          [[ "$(git status -s)" != "" ]] && echo "status=1" >> "$GITHUB_OUTPUT" || echo "status=0" >> "$GITHUB_OUTPUT"
      - name: Commit change
        if: ${{ steps.status.outputs.status == 1 }}
        run: |
          git add -A
          git commit -m "Updating submodule $(date)"
          git push origin main
