name: Submodules Update for Customer Configuration Repositories

on:
  workflow_dispatch:

jobs:
  get-repo-list:
    runs-on: ubuntu-latest
    outputs:
      repolist: ${{ steps.repolist.outputs.repolist }}
    steps:
      - uses: actions/checkout@v3
      - name: Read config.list
        id: repolist
        run: |
          list=$(cat config.list | tr "\n" ",")
          echo "repolist=[${list::-1}]" >> "$GITHUB_OUTPUT"
  trigger-repo-update:
    runs-on: ubuntu-latest
    needs: get-repo-list
    strategy:
      matrix:
        repository: ${{ needs.get-repo-list.outputs.repolist }}
    steps:
      - name: Trigger update
        run: |
          echo ${{ matrix.repository }}
