name: Submodules Update for Customer Configuration Repositories

on:
  workflow_call:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule update --remote
          git status
